server:
  port: 9000
spring:
  application:
    name: service-hi
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource

#  fdfs.pool.max-wait-millis = 100
#  fdfs.pool.jmx-name-base = 1
#  fdfs.pool.jmx-name-prefix = 1
fdfs:
  so-timeout: 90000
  connect-timeout: 90000

  thumb-image:
    width: 150
    height: 150
  tracker-list:
     - 103.40.232.189:22122
      # - 103.40.232.190:22122
  pool:
    max-wait-millis: 100
    jmx-name-base: 1
    jmx-name-prefix: 1
    max-total: 1000
#eureka.instace.hostname=127.0.0.1
##注册中心不需要注册自己
#eureka
#  client
#   register-with-eureka:false
#eureka.client.fetch-registry=false
#eureka.client.serviceUrl.defaultZone=http://127.0.0.1:1111/eureka/
#pool.max-total = 200
eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    #register-with-eureka: true
