server:
  port: 8988
spring:
  application:
    name: service-hi
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
#  zipkin:
#    base-url: http://localhost:9411

fdfs:
  so-timeout: 90000
  connect-timeout: 90000
  thumb-image:
    width: 150
    height: 150
  tracker-list:
     - 103.40.232.189:22122
     - 103.40.232.190:22122

