server:
  port: 8988
spring:
  application:
    name: service-hi
  datasource:
    name: druidDataSource
    type: com.alibaba.druid.pool.DruidDataSource
#  zipkin:
#    base-url: http://localhost:9411

fastdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址
    - 103.40.232.190:22122
    - 103.40.232.189:22122

